# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Book title')),
                ('author', models.CharField(max_length=256, verbose_name='Author info')),
                ('ISBN', models.CharField(max_length=13, verbose_name='International\tStandard Book Number')),
                ('price', models.IntegerField(verbose_name='Book price (in cents)')),
            ],
        ),
    ]
