# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 15:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Publish Date'),
        ),
    ]
