# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 01:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_logginginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logginginfo',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Book'),
        ),
        migrations.AlterField(
            model_name='logginginfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
